<a href="https://colab.research.google.com/github/gardenstorm/Genshin-Wish-Visualization/blob/main/Genshin_Wish_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🌠 Genshin Wish Visualization
As a version 1.1 player, I have over 5 years of wish data that I have been recording. Inspired by the website Paimon.moe, I want to create my own visualizations of my wish data. I have tried making some charts and pivot tables in Excel, but wasn't satisfied. So I wanted to do this the fun way: with Python. 😎

## 📊 The Data
There are 2 sets of data:

1. An Excel spreadsheet I created:
- Started in 2020
- Has only the date for timestamp
- Character name instead of full banner name
- I stopped using some columns
- Until January 2025


2. An Excel spreadsheet exported from paimon.moe:
- Started using the site in 2021
- List of banner names
- Complete timestamps
- Group column (10 pull batches)
- Up to late February 2026

## What I Want to Visualize
- How many 5 stars I have ✅
- What 4 stars I get the most ✅
- What weapon I get the most ✅
- My win rate ✅
- How many early 5 stars ✅
- My average pity ✅

## 🛠️ Putting together the data
According to my data, I started using Paimon.moe in August of 2021. So from my personal spreadsheet I will add data from before that date onto to the Paimon.moe one.

I will use the columns both datasets have in common in the order Paimon.moe has:
- Type: Character or weapon
- Name
- Time
- ⭐: Rarity, goes from 3-5
- Pity: 4 star pity count
- Roll #: 5 star pity count
- Banner

Maybe keep the Wish # column from my personal spreadsheet? It's fun to see that count. (It's in the thousands!)

Naturally, I will need to reorder my personal spreadsheet columns.

Tools used:
- Python
 - Pandas
- Google Drive
- Google Colab
- Google Sheets

File names:
- paimonmoe_wish_history.xlsx
- Genshin Wish Tracker.xlsx

In [1]:
import pandas as pd
import numpy as np

### My personal Excel sheet

- Loading the Excel file
- Only using rows up to August 2021 with `.head()`
- Setting the 1st row as the header and "Wish #" as index column
- Dropping columns I'm not using

In [2]:
# load the Excel file and start a df
personal = pd.ExcelFile('/content/drive/MyDrive/Genshin Wish Tracker.xlsx')
ps_limited = pd.read_excel(personal, sheet_name='Event Banner', header=1, index_col=0).head(225).drop(columns=['Notes', '10 Pull?'])
ps_limited

,Wish Date,Type,Wish Result,Rarity,Banner,4¶ Pity,5¶ Pity
Wish #,,,,,,,
1,2020-12-16 00:00:00,Character,Beidou,4,Zhongli 1st,1.0,1
2,2020-12-16 00:00:00,Weapon,Harbinger of Dawn,3,Zhongli 1st,NaN,2
3,2020-12-16 00:00:00,Weapon,Harbinger of Dawn,3,Zhongli 1st,NaN,3
4,2020-12-18 00:00:00,Weapon,Raven Bow,3,Zhongli 1st,NaN,4
5,2020-12-18 00:00:00,Weapon,Harbinger of Dawn,3,Zhongli 1st,NaN,5
...,...,...,...,...,...,...,...
221,2021-05-15 00:00:00,Character,Bennett,4,Zhongli 2nd,5.0,75
222,2021-05-15 00:00:00,Character,Qiqi,5,Zhongli 2nd,1.0,76
223,2021-05-17 00:00:00,Weapon,Magic Guide,3,Zhongli 2nd,1.0,1
224,2021-05-17 00:00:00,Weapon,Raven Bow,3,Zhongli 2nd,2.0,2
225,2021-05-17 00:00:00,Weapon,Slingshot,3,Zhongli 2nd,3.0,3

Reordering the columns

In [3]:
# List of column names to copy and paste
ps_limited.columns.values

array(['Wish Date', 'Type', 'Wish Result', 'Rarity', 'Banner', '4¶ Pity',
       '5¶  Pity'], dtype=object)

In [4]:
ps_limited_ro = ps_limited[['Type', 'Wish Result', 'Wish Date', 'Rarity', '4¶ Pity', '5¶  Pity', 'Banner']]
ps_limited_ro

,Type,Wish Result,Wish Date,Rarity,4¶ Pity,5¶ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16 00:00:00,4,1.0,1,Zhongli 1st
2,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,NaN,2,Zhongli 1st
3,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,NaN,3,Zhongli 1st
4,Weapon,Raven Bow,2020-12-18 00:00:00,3,NaN,4,Zhongli 1st
5,Weapon,Harbinger of Dawn,2020-12-18 00:00:00,3,NaN,5,Zhongli 1st
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15 00:00:00,4,5.0,75,Zhongli 2nd
222,Character,Qiqi,2021-05-15 00:00:00,5,1.0,76,Zhongli 2nd
223,Weapon,Magic Guide,2021-05-17 00:00:00,3,1.0,1,Zhongli 2nd
224,Weapon,Raven Bow,2021-05-17 00:00:00,3,2.0,2,Zhongli 2nd
225,Weapon,Slingshot,2021-05-17 00:00:00,3,3.0,3,Zhongli 2nd

Renaming the columns to:
- match the paimon.moe sheet
- have more intuitive names

In [5]:
ps_limited_almost = ps_limited_ro.rename(index=str, columns={'Wish Date': 'Time', '4¶ Pity': '4⭐ Pity', '5¶  Pity': '5⭐ Pity'})
ps_limited_almost

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16 00:00:00,4,1.0,1,Zhongli 1st
2,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,NaN,2,Zhongli 1st
3,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,NaN,3,Zhongli 1st
4,Weapon,Raven Bow,2020-12-18 00:00:00,3,NaN,4,Zhongli 1st
5,Weapon,Harbinger of Dawn,2020-12-18 00:00:00,3,NaN,5,Zhongli 1st
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15 00:00:00,4,5.0,75,Zhongli 2nd
222,Character,Qiqi,2021-05-15 00:00:00,5,1.0,76,Zhongli 2nd
223,Weapon,Magic Guide,2021-05-17 00:00:00,3,1.0,1,Zhongli 2nd
224,Weapon,Raven Bow,2021-05-17 00:00:00,3,2.0,2,Zhongli 2nd
225,Weapon,Slingshot,2021-05-17 00:00:00,3,3.0,3,Zhongli 2nd

Filling in 4⭐Pity's `NaN` values with `.interpolate()` and keeping the data type as INT with `.astype()`

In [6]:
ps_limited_almost['4⭐ Pity'] = ps_limited_almost['4⭐ Pity'].interpolate(method='linear').astype(int)
ps_limited_almost

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16 00:00:00,4,1,1,Zhongli 1st
2,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,1,2,Zhongli 1st
3,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,2,3,Zhongli 1st
4,Weapon,Raven Bow,2020-12-18 00:00:00,3,3,4,Zhongli 1st
5,Weapon,Harbinger of Dawn,2020-12-18 00:00:00,3,4,5,Zhongli 1st
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15 00:00:00,4,5,75,Zhongli 2nd
222,Character,Qiqi,2021-05-15 00:00:00,5,1,76,Zhongli 2nd
223,Weapon,Magic Guide,2021-05-17 00:00:00,3,1,1,Zhongli 2nd
224,Weapon,Raven Bow,2021-05-17 00:00:00,3,2,2,Zhongli 2nd
225,Weapon,Slingshot,2021-05-17 00:00:00,3,3,3,Zhongli 2nd

Convert "Time" column to datetime to make filtering and searching easier

In [7]:
ps_limited_almost["Time"] = pd.to_datetime(ps_limited_almost["Time"], format='%Y-%m-%d %H:%M:%S')
ps_limited_almost

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16,4,1,1,Zhongli 1st
2,Weapon,Harbinger of Dawn,2020-12-16,3,1,2,Zhongli 1st
3,Weapon,Harbinger of Dawn,2020-12-16,3,2,3,Zhongli 1st
4,Weapon,Raven Bow,2020-12-18,3,3,4,Zhongli 1st
5,Weapon,Harbinger of Dawn,2020-12-18,3,4,5,Zhongli 1st
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15,4,5,75,Zhongli 2nd
222,Character,Qiqi,2021-05-15,5,1,76,Zhongli 2nd
223,Weapon,Magic Guide,2021-05-17,3,1,1,Zhongli 2nd
224,Weapon,Raven Bow,2021-05-17,3,2,2,Zhongli 2nd
225,Weapon,Slingshot,2021-05-17,3,3,3,Zhongli 2nd

Remove 1st, 2nd, etc. from banner names

In [8]:
ps_limited_almost['Banner'] = ps_limited_almost['Banner'].str.replace(r"\s\d[a-z]+", "", regex=True)
ps_limited_almost

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16,4,1,1,Zhongli
2,Weapon,Harbinger of Dawn,2020-12-16,3,1,2,Zhongli
3,Weapon,Harbinger of Dawn,2020-12-16,3,2,3,Zhongli
4,Weapon,Raven Bow,2020-12-18,3,3,4,Zhongli
5,Weapon,Harbinger of Dawn,2020-12-18,3,4,5,Zhongli
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15,4,5,75,Zhongli
222,Character,Qiqi,2021-05-15,5,1,76,Zhongli
223,Weapon,Magic Guide,2021-05-17,3,1,1,Zhongli
224,Weapon,Raven Bow,2021-05-17,3,2,2,Zhongli
225,Weapon,Slingshot,2021-05-17,3,3,3,Zhongli

Change VENTI to Venti

In [9]:
ps_limited_almost['Wish Result'] = ps_limited_almost['Wish Result'].str.replace('VENTI', 'Venti')
ps_limited_almost

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
Wish #,,,,,,,
1,Character,Beidou,2020-12-16,4,1,1,Zhongli
2,Weapon,Harbinger of Dawn,2020-12-16,3,1,2,Zhongli
3,Weapon,Harbinger of Dawn,2020-12-16,3,2,3,Zhongli
4,Weapon,Raven Bow,2020-12-18,3,3,4,Zhongli
5,Weapon,Harbinger of Dawn,2020-12-18,3,4,5,Zhongli
...,...,...,...,...,...,...,...
221,Character,Bennett,2021-05-15,4,5,75,Zhongli
222,Character,Qiqi,2021-05-15,5,1,76,Zhongli
223,Weapon,Magic Guide,2021-05-17,3,1,1,Zhongli
224,Weapon,Raven Bow,2021-05-17,3,2,2,Zhongli
225,Weapon,Slingshot,2021-05-17,3,3,3,Zhongli

### Paimon.moe Excel sheet

🧚Paimon.moe data loaded, sans unused columns

In [10]:
paimon = pd.ExcelFile('/content/drive/MyDrive/paimonmoe_wish_history.xlsx')
pm_limited = pd.read_excel(paimon, sheet_name='Character Event').drop(columns=['Group', 'Part'])
pm_limited

,Type,Name,Time,⭐,Pity,#Roll,Banner
0,Character,Beidou,2020-12-16 16:51:04,4,1,1,Gentry of Hermitage
1,Weapon,Harbinger of Dawn,2020-12-16 16:51:47,3,1,2,Gentry of Hermitage
2,Weapon,Harbinger of Dawn,2020-12-16 16:53:11,3,1,3,Gentry of Hermitage
3,Weapon,Raven Bow,2020-12-18 16:53:41,3,1,4,Gentry of Hermitage
4,Weapon,Harbinger of Dawn,2020-12-18 16:54:13,3,1,5,Gentry of Hermitage
...,...,...,...,...,...,...,...
1774,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,6,Decree of the Deeps
1775,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,7,Decree of the Deeps
1776,Weapon,Debate Club,2026-02-05 20:31:59,3,1,8,Decree of the Deeps
1777,Weapon,Slingshot,2026-02-05 20:31:59,3,1,9,Decree of the Deeps
1778,Character,Dehya,2026-02-05 20:31:59,5,10,10,Decree of the Deeps

Removing columns before August 2021 and converting the "Time" column to datetime

In [11]:
# convert "Time" col to datetime
pm_limited['Time'] = pd.to_datetime(pm_limited['Time'], format='%Y-%m-%d %H:%M:%S')

# filter out lines from before August 2021
pm_limited_filtered = pm_limited.query("Time >= '2021-08-01'")
pm_limited_filtered

,Type,Name,Time,⭐,Pity,#Roll,Banner
11,Weapon,Bloodtainted Greatsword,2021-08-12 14:06:37,3,1,1,Tapestry of Golden Flames
12,Weapon,Raven Bow,2021-08-12 14:06:48,3,1,2,Tapestry of Golden Flames
13,Weapon,Magic Guide,2021-08-12 14:07:00,3,1,3,Tapestry of Golden Flames
14,Character,Xinyan,2021-08-12 14:07:20,4,4,4,Tapestry of Golden Flames
15,Weapon,Harbinger of Dawn,2021-08-12 17:47:22,3,1,5,Tapestry of Golden Flames
...,...,...,...,...,...,...,...
1774,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,6,Decree of the Deeps
1775,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,7,Decree of the Deeps
1776,Weapon,Debate Club,2026-02-05 20:31:59,3,1,8,Decree of the Deeps
1777,Weapon,Slingshot,2026-02-05 20:31:59,3,1,9,Decree of the Deeps
1778,Character,Dehya,2026-02-05 20:31:59,5,10,10,Decree of the Deeps

Change the formal banner names to character names
- More intuitive for me
- Will fit in visualizations better

In [12]:
# load the csv into a df
banner_csv = pd.read_csv('/content/drive/MyDrive/Genshin Banners.csv')

# set "Name" col as the index
banner_dict = banner_csv.set_index('Name')

# turn the df into a dict
banner_dict = banner_dict['Character'].to_dict()

# make the swaps!
pm_limited_filtered = pm_limited_filtered.copy()
pm_limited_filtered.loc[:, 'Banner'] = pm_limited_filtered['Banner'].map(banner_dict)
pm_limited_filtered

,Type,Name,Time,⭐,Pity,#Roll,Banner
11,Weapon,Bloodtainted Greatsword,2021-08-12 14:06:37,3,1,1,Yoimiya
12,Weapon,Raven Bow,2021-08-12 14:06:48,3,1,2,Yoimiya
13,Weapon,Magic Guide,2021-08-12 14:07:00,3,1,3,Yoimiya
14,Character,Xinyan,2021-08-12 14:07:20,4,4,4,Yoimiya
15,Weapon,Harbinger of Dawn,2021-08-12 17:47:22,3,1,5,Yoimiya
...,...,...,...,...,...,...,...
1774,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,6,Neuvillette
1775,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,7,Neuvillette
1776,Weapon,Debate Club,2026-02-05 20:31:59,3,1,8,Neuvillette
1777,Weapon,Slingshot,2026-02-05 20:31:59,3,1,9,Neuvillette
1778,Character,Dehya,2026-02-05 20:31:59,5,10,10,Neuvillette

Change the column names to match `ps_limited_almost`

In [13]:
pm_limited_filtered = pm_limited_filtered.rename(index=str, columns={'Name' : 'Wish Result', '⭐': 'Rarity', 'Pity': '4⭐ Pity', '#Roll': '5⭐ Pity'})
pm_limited_filtered

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
11,Weapon,Bloodtainted Greatsword,2021-08-12 14:06:37,3,1,1,Yoimiya
12,Weapon,Raven Bow,2021-08-12 14:06:48,3,1,2,Yoimiya
13,Weapon,Magic Guide,2021-08-12 14:07:00,3,1,3,Yoimiya
14,Character,Xinyan,2021-08-12 14:07:20,4,4,4,Yoimiya
15,Weapon,Harbinger of Dawn,2021-08-12 17:47:22,3,1,5,Yoimiya
...,...,...,...,...,...,...,...
1774,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,6,Neuvillette
1775,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,7,Neuvillette
1776,Weapon,Debate Club,2026-02-05 20:31:59,3,1,8,Neuvillette
1777,Weapon,Slingshot,2026-02-05 20:31:59,3,1,9,Neuvillette
1778,Character,Dehya,2026-02-05 20:31:59,5,10,10,Neuvillette

Combine the data frames with `concat()`

In [14]:
ps_limited_almost = ps_limited_almost.reset_index(drop=True)
wish_data = pd.concat([ps_limited_almost, pm_limited_filtered]).reset_index(drop=True)
wish_data

,Type,Wish Result,Time,Rarity,4⭐ Pity,5⭐ Pity,Banner
0,Character,Beidou,2020-12-16 00:00:00,4,1,1,Zhongli
1,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,1,2,Zhongli
2,Weapon,Harbinger of Dawn,2020-12-16 00:00:00,3,2,3,Zhongli
3,Weapon,Raven Bow,2020-12-18 00:00:00,3,3,4,Zhongli
4,Weapon,Harbinger of Dawn,2020-12-18 00:00:00,3,4,5,Zhongli
...,...,...,...,...,...,...,...
1986,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,6,Neuvillette
1987,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,7,Neuvillette
1988,Weapon,Debate Club,2026-02-05 20:31:59,3,1,8,Neuvillette
1989,Weapon,Slingshot,2026-02-05 20:31:59,3,1,9,Neuvillette
1990,Character,Dehya,2026-02-05 20:31:59,5,10,10,Neuvillette

## 🔎Processing the Data

### How many 5 star characters from limited banners

In [15]:
# how many 5 stars I've pulled from event banners
ssr = wish_data[wish_data['Rarity'] == 5]
ssr['Wish Result'].nunique()

23

In [16]:
# list of 5 star characters and times pulled
ssr['Wish Result'].value_counts()

Wish Result
Keqing              6
Diluc               2
Wanderer            2
Qiqi                1
Raiden Shogun       1
Ganyu               1
Venti               1
Zhongli             1
Albedo              1
Nahida              1
Xiao                1
Kaedehara Kazuha    1
Furina              1
Navia               1
Neuvillette         1
Mualani             1
Kinich              1
Citlali             1
Skirk               1
Mavuika             1
Durin               1
Columbina           1
Dehya               1
Name: count, dtype: int64

### Most pulled weapons

In [17]:
# most pulled weapons
weapons = wish_data[wish_data['Type'] == 'Weapon']
weapons['Wish Result'].value_counts()

Wish Result
Sharpshooter's Oath                  147
Raven Bow                            142
Ferrous Shadow                       139
Thrilling Tales of Dragon Slayers    137
Cool Steel                           136
Black Tassel                         133
Skyrider Sword                       129
Harbinger of Dawn                    123
Debate Club                          123
Emerald Orb                          121
Magic Guide                          120
Bloodtainted Greatsword              119
Slingshot                            119
Bloodstained Greatsword               16
The Stringless                         7
Dragon's Bane                          6
Sacrificial Bow                        6
Favonius Lance                         6
Rainslasher                            5
Rust                                   5
The Bell                               5
Sacrificial Greatsword                 4
The Widsith                            4
Eye of Perception                      4
Favonius Sword                         3
Sacrificial Fragments                  3
Favonius Codex                         3
Sacrificial Sword                      3
Favonius Greatsword                    3
Lion's Roar                            2
Favonius Warbow                        2
The Flute                              1
Favonious Codex                        1
Name: count, dtype: int64

### Most pulled 4 stars

In [18]:
# most pulled 4 star weapons
weapons = wish_data[(wish_data['Type'] == 'Weapon') & (wish_data['Rarity'] == 4)]
weapons['Wish Result'].value_counts()

Wish Result
The Stringless            7
Dragon's Bane             6
Sacrificial Bow           6
Favonius Lance            6
Rainslasher               5
Rust                      5
The Bell                  5
Sacrificial Greatsword    4
The Widsith               4
Eye of Perception         4
Favonius Sword            3
Sacrificial Fragments     3
Favonius Codex            3
Sacrificial Sword         3
Favonius Greatsword       3
Lion's Roar               2
Favonius Warbow           2
The Flute                 1
Favonious Codex           1
Name: count, dtype: int64

In [19]:
# now let's get characters
characters = wish_data[(wish_data['Type'] == 'Character') & (wish_data['Rarity'] == 4)]
characters['Wish Result'].value_counts()

Wish Result
Beidou              16
Yanfei              12
Diona               11
Sucrose             11
Faruzan             11
Bennett             10
Noelle               8
Xiangling            8
Fischl               7
Shikanoin Heizou     6
Xingqiu              5
Ningguang            5
Iansan               5
Rosaria              5
Dori                 4
Sayu                 4
Jahoda               4
Barbara              4
Thoma                4
Xinyan               3
Yaoyao               3
Layla                3
Razor                3
Kuki Shinobu         3
Kujou Sara           3
Chevreuse            3
Kaveh                2
Gorou                2
Gaming               2
Charlotte            2
Candace              2
Lynette              2
Ifa                  2
Sethos               2
Freminet             2
Collei               1
Yun Jin              1
Kachina              1
Kirara               1
Illuga               1
Name: count, dtype: int64

### 50/50 luck

In [20]:
# Claude helped with the formula. I came up with the True/False table!
wins = (ssr['Wish Result'] == ssr['Banner']) == True
wins_values = wins.value_counts()
win_rate_5stars = (wins_values[True] - wins_values[False]) / wins_values[True] * 100
win_rate_5stars

np.float64(50.0)

In [21]:
wins_values

True     20
False    10
Name: count, dtype: int64

### Early 5 stars
According to [game8](https://game8.co/games/Genshin-Impact/archives/305937), Genshin's pity system has soft pity between pulls 60 - 80. Hard pity is after 80, and if a 5 star character on the limited banner is guranteed at 90 pity if one isn't received earlier. So, we count 5 stars before hard pity as "early". The earlier the 5 star, the more exciting it is!

I chose 70 as a midpoint between 60 and 80.

#### ⚠️ Note:
I misinterpreted what 2 of Paimon.moe's columns meant here and need to rename them to what they were originally: `Pity` and `#Roll`.
- `Pity` is the pity count for both 4 and 5 stars.
- `#Roll` is the number of rolls on the banner.
  - I want to rename this column to something clearer.

In [22]:
early_5s = ssr[(ssr['4⭐ Pity'] < 70)].drop(columns=['Type', 'Time', 'Rarity', '5⭐ Pity'])
early_5s

     Wish Result  4⭐ Pity       Banner
64        Keqing        6        Ganyu
66         Ganyu        2        Ganyu
139        Venti        8        Venti
221         Qiqi        1      Zhongli
847       Keqing       16        Ayaka
1352    Wanderer       52     Wanderer
1532      Kinich       29       Kinich
1736       Skirk       51        Skirk
1990       Dehya       10  Neuvillette

### Average Pity
Pretty simple: The average of the Pity column.

In [23]:
avg_pity = ssr['4⭐ Pity'].mean().astype(int)
avg_pity

np.int64(59)

My pity doesn't feel that good most of the time. Let's try mode and median.

In [24]:
med_pity = ssr['4⭐ Pity'].median()
med_pity

75.5

In [25]:
mode_pity = ssr['4⭐ Pity'].mode()
mode_pity

0    76
Name: 4⭐ Pity, dtype: int64

That's closer to what I feel most of the time: 75 or 76 pulls.

## ⏩ Functions to go faster
Now that I hashed out my data, let's make the code more functional and pythonic.

Functions:
1. Loading the Excel sheet and general adjustments
2. Banner column stuff
3. Merging
4. My 6 questions

The other code is too finicky to put into functions.

### 🕑 Loading the Excel sheet
- Docstring to specify Excel file only
- Parameters:
  - `file`, `sheet_name`, `drop_columns`, `time_convert`

In [26]:
# loading the Excel sheet
def load_file(file, sheet, drop_columns, time_convert):
  """Loads the Excel file, selects the relevant sheet,
  drops unused columns, and converts one column to datetime.
  > file: Excel file to load as a string
  > sheet: Name of the sheet to use as a string
  > drop_columns: List of columns to drop, each column a string
  > time_convert: Column name to convert to datetime format"""
  # load the Excel file a datafrme
  to_load = pd.ExcelFile(file)
  # selects the specified sheet and drops designated columns
  loaded = pd.read_excel(to_load, sheet_name=sheet).drop(columns=drop_columns)
  # convert the designated column to datetime and this format: YYYY-MM-DD HH:MM:SS
  loaded[time_convert] = pd.to_datetime(loaded[time_convert], format='%Y-%m-%d %H:%M:%S')
  return loaded

In [27]:
test = load_file('/content/drive/MyDrive/paimonmoe_wish_history.xlsx', 'Standard', ['#Roll', 'Group', 'Part'], 'Time')

In [28]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Type    399 non-null    object
 1   Name    399 non-null    object
 2   Time    399 non-null    datetime64[ns]
 3   ⭐       399 non-null    int64
 4   Pity    399 non-null    int64
 5   Banner  399 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 18.8+ KB

### 📝 Change banner names to character names and title case
- Use RegEx to filter out 1st, 2nd, etc.
- Use `map` or `apply` with a dictionary filled with banner and character name mappings
 - Used Gemini inside Colab to fix an error
   - Tried to use `replace`, but it didn't work.
   - Colab fixed the code to use map instead
- Use `str.title()` to make character names look like names

In [29]:
def banner_col_changes(dict_csv, df_name, col_name):
  """Filters out ordinal numbers, changes banner names
  to character names, and makes character names title case.
  > dict_csv: Path to my banner names dictionary file
  > df_name: name of dataframe to make changes on
  > col_name: Column to make changes to"""
  # load the dictionary file
  banner_csv = pd.read_csv(dict_csv)
  # convert banner_csv to a dictionary
  mapping_dict = banner_csv.set_index('Name')['Character'].to_dict()
  # filter out ordinals
  df_name[col_name] = df_name[col_name].str.replace(r"\s\d[a-z]+", "", regex=True)
  # Map the dictionary to switch to character names instead of long banner names
  df_name[col_name] = df_name[col_name].map(mapping_dict)
  # Title case the column
  df_name[col_name] = df_name[col_name].apply(str.title)
  return df_name

In [30]:
test2 = load_file('/content/drive/MyDrive/paimonmoe_wish_history.xlsx', 'Character Event', ['#Roll', 'Group', 'Part'], 'Time')
banner_test = banner_col_changes('/content/drive/MyDrive/Genshin Banners.csv', test2, 'Banner')
banner_test

,Type,Name,Time,⭐,Pity,Banner
0,Character,Beidou,2020-12-16 16:51:04,4,1,Zhongli
1,Weapon,Harbinger of Dawn,2020-12-16 16:51:47,3,1,Zhongli
2,Weapon,Harbinger of Dawn,2020-12-16 16:53:11,3,1,Zhongli
3,Weapon,Raven Bow,2020-12-18 16:53:41,3,1,Zhongli
4,Weapon,Harbinger of Dawn,2020-12-18 16:54:13,3,1,Zhongli
...,...,...,...,...,...,...
1774,Weapon,Thrilling Tales of Dragon Slayers,2026-02-05 20:31:59,3,1,Neuvillette
1775,Weapon,Magic Guide,2026-02-05 20:31:59,3,1,Neuvillette
1776,Weapon,Debate Club,2026-02-05 20:31:59,3,1,Neuvillette
1777,Weapon,Slingshot,2026-02-05 20:31:59,3,1,Neuvillette
1778,Character,Dehya,2026-02-05 20:31:59,5,10,Neuvillette

###